# Unique project key you set when creating it in SonarQube
sonar.projectKey=react-node-app

# Display name in SonarQube dashboard
sonar.projectName=React Node App

# Version (optional)
sonar.projectVersion=1.0

# The folder containing your source code
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# Ignore these files/folders
sonar.exclusions=**/node_modules/**,**/*.test.js,**/__tests__/**

# (Optional) Test coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Your local SonarQube server
sonar.host.url=http://localhost:9000

# The token you generated in SonarQube
sonar.login=sqp_48358122a87ada6ecadf1b344b183e673643c609
